spring:
  application:
    name: e-commerce
  datasource:
    url: jdbc:mysql://localhost:3307/ecommerce
    username: root
    password: 15122004

  jpa:
    properties:
      hibernate:
        format_sql: true
    # Uncomment if needed
    # hibernate:
    #   ddl-auto: update

  jackson:
  # Uncomment if needed
  # date-format: dd-MM-yyyy HH:mm:ss
  # serialization:
  #   write-dates-as-timestamps: false

  elasticsearch:
    uris: http://localhost:9200
    username: docker-cluster
    password: 090224T@n
    index-recovery:
      mode: full  # Make sure recovery mode is set to full
  kafka:
    bootstrap-servers: 127.0.0.1:9091,127.0.0.1:9092,127.0.0.1:9093
    consumer:
      group-id: search-asycn
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.apache.http: DEBUG
    root: warn
    org:
      hibernate:
        SQL: debug
      hibernate.orm.jdbc.bind: trace
      springframework.security: DEBUG

lombok:
  anyConstructor:
    addConstructorProperties: true

application:
  security:
    jwt:
      secret-key: VBLoLSe1wHc3a4SelQyKN2uExewLWNeTF1XY2EqrFQjuFGtgxtYBXKCPfwqGNrMP
      expiration: 86400 # a day
      refresh-token:
        expiration: 604800 # a week
  kafka:
    topics:
      topic1: "dbs_.ecommerce.product"
      topic2: "dbs_.ecommerce.sku"
      topic3: "dbs_.ecommerce.category"
      topic4: "dbs_.ecommerce.options"
      topic5: "dbs_.ecommerce.option_value"


payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: MEBTRFP0
    secretKey: XGR3PAJ4STE368KZBJQ2GO2KJBS1R6HF
    returnUrl: http://localhost:8080/api/v1/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: Thanh toan don hang
